# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/mnist_design_smartconnect_0_0.xci
# IP: The module: 'mnist_design_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/bd_e620.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_0/bd_e620_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_2/bd_e620_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_3/bd_e620_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_4/bd_e620_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_5/bd_e620_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_6/bd_e620_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_7/bd_e620_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_8/bd_e620_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_9/bd_e620_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_10/bd_e620_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_11/bd_e620_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_12/bd_e620_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_13/bd_e620_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_14/bd_e620_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_15/bd_e620_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_16/bd_e620_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_17/bd_e620_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_18/bd_e620_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_19/bd_e620_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_20/bd_e620_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_21/bd_e620_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_22/bd_e620_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_23/bd_e620_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_24/bd_e620_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_25/bd_e620_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_26/bd_e620_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_27/bd_e620_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_28/bd_e620_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_29/bd_e620_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_30/bd_e620_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_31/bd_e620_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_32/bd_e620_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_33/bd_e620_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_34/bd_e620_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_35/bd_e620_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_36/bd_e620_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_37/bd_e620_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_38/bd_e620_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_39/bd_e620_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_40/bd_e620_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_41/bd_e620_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_42/bd_e620_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_43/bd_e620_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_2/bd_e620_arsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_3/bd_e620_rsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_4/bd_e620_awsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_5/bd_e620_wsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_6/bd_e620_bsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_10/bd_e620_s00a2s_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_11/bd_e620_sarn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_12/bd_e620_srn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_13/bd_e620_sawn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_14/bd_e620_swn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_15/bd_e620_sbn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_16/bd_e620_m00s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_17/bd_e620_m00arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_18/bd_e620_m00rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_19/bd_e620_m00awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_20/bd_e620_m00wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_21/bd_e620_m00bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_23/bd_e620_m01s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_24/bd_e620_m01arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_25/bd_e620_m01rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_26/bd_e620_m01awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_27/bd_e620_m01wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_28/bd_e620_m01bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_30/bd_e620_m02s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_31/bd_e620_m02arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_32/bd_e620_m02rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_33/bd_e620_m02awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_34/bd_e620_m02wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_35/bd_e620_m02bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_37/bd_e620_m03s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_38/bd_e620_m03arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_39/bd_e620_m03rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_40/bd_e620_m03awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_41/bd_e620_m03wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_42/bd_e620_m03bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_design_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/mnist_design_smartconnect_0_0.xci
# IP: The module: 'mnist_design_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/bd_e620.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_0/bd_e620_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_2/bd_e620_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_3/bd_e620_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_4/bd_e620_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_5/bd_e620_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_6/bd_e620_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_7/bd_e620_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_8/bd_e620_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_9/bd_e620_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_10/bd_e620_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_11/bd_e620_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_12/bd_e620_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_13/bd_e620_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_14/bd_e620_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_15/bd_e620_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_16/bd_e620_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_17/bd_e620_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_18/bd_e620_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_19/bd_e620_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_20/bd_e620_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_21/bd_e620_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_22/bd_e620_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_23/bd_e620_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_24/bd_e620_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_25/bd_e620_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_26/bd_e620_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_27/bd_e620_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_28/bd_e620_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_29/bd_e620_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_30/bd_e620_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_31/bd_e620_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_32/bd_e620_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_33/bd_e620_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_34/bd_e620_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_35/bd_e620_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_36/bd_e620_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_37/bd_e620_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_38/bd_e620_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_39/bd_e620_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_40/bd_e620_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_41/bd_e620_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_42/bd_e620_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_43/bd_e620_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_2/bd_e620_arsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_3/bd_e620_rsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_4/bd_e620_awsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_5/bd_e620_wsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_6/bd_e620_bsw_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_10/bd_e620_s00a2s_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_11/bd_e620_sarn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_12/bd_e620_srn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_13/bd_e620_sawn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_14/bd_e620_swn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_15/bd_e620_sbn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_16/bd_e620_m00s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_17/bd_e620_m00arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_18/bd_e620_m00rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_19/bd_e620_m00awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_20/bd_e620_m00wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_21/bd_e620_m00bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_23/bd_e620_m01s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_24/bd_e620_m01arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_25/bd_e620_m01rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_26/bd_e620_m01awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_27/bd_e620_m01wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_28/bd_e620_m01bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_30/bd_e620_m02s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_31/bd_e620_m02arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_32/bd_e620_m02rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_33/bd_e620_m02awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_34/bd_e620_m02wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_35/bd_e620_m02bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_37/bd_e620_m03s2a_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_38/bd_e620_m03arn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_39/bd_e620_m03rn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_40/bd_e620_m03awn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_41/bd_e620_m03wn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_42/bd_e620_m03bn_0_ooc.xdc

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_design_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
