# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_xbar_1/mnist_design_xbar_1.xci
# IP: The module: 'mnist_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_xbar_1/mnist_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_xbar_1/mnist_design_xbar_1.xci
# IP: The module: 'mnist_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_xbar_1/mnist_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
