# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/¾G¨|¥à/Desktop/pynq-z2_v1.0.xdc

# Block Designs: bd/mnist_design/mnist_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design || ORIG_REF_NAME==mnist_design} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_conv_0_0/mnist_design_conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_conv_0_0 || ORIG_REF_NAME==mnist_design_conv_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_processing_system7_0_0/mnist_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_processing_system7_0_0 || ORIG_REF_NAME==mnist_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_axi_cdma_0_0/mnist_design_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_axi_cdma_0_0 || ORIG_REF_NAME==mnist_design_axi_cdma_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_axi_gpio_0_0/mnist_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_axi_gpio_0_0 || ORIG_REF_NAME==mnist_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_axi_bram_ctrl_0_0/mnist_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mnist_design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_axi_bram_ctrl_1_0/mnist_design_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_axi_bram_ctrl_1_0 || ORIG_REF_NAME==mnist_design_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_axi_bram_ctrl_2_0/mnist_design_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_axi_bram_ctrl_2_0 || ORIG_REF_NAME==mnist_design_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_blk_mem_gen_0_0/mnist_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_blk_mem_gen_0_0 || ORIG_REF_NAME==mnist_design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_blk_mem_gen_1_0/mnist_design_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_blk_mem_gen_1_0 || ORIG_REF_NAME==mnist_design_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_blk_mem_gen_2_0/mnist_design_blk_mem_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_blk_mem_gen_2_0 || ORIG_REF_NAME==mnist_design_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_proc_sys_reset_0_0/mnist_design_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_proc_sys_reset_0_0 || ORIG_REF_NAME==mnist_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_xbar_0/mnist_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_xbar_0 || ORIG_REF_NAME==mnist_design_xbar_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_axi_interconnect_0_0/mnist_design_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_axi_interconnect_0_0 || ORIG_REF_NAME==mnist_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_smartconnect_0_0/mnist_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_smartconnect_0_0 || ORIG_REF_NAME==mnist_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_xbar_1/mnist_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_xbar_1 || ORIG_REF_NAME==mnist_design_xbar_1} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_ps7_0_axi_periph_0/mnist_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==mnist_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mnist_design/ip/mnist_design_auto_pc_0/mnist_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_design_auto_pc_0 || ORIG_REF_NAME==mnist_design_auto_pc_0} -quiet] -quiet

# XDC: bd/mnist_design/mnist_design_ooc.xdc
