# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/mnist_vivado/mnist_vivado.cache/wt [current_project]
set_property parent.project_path D:/mnist_vivado/mnist_vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths d:/mnist_convo_circuit [current_project]
update_ip_catalog
set_property ip_output_repo d:/mnist_vivado/mnist_vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/hdl/mnist_design_wrapper.v
add_files D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/mnist_design.bd
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_processing_system7_0_0/mnist_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_cdma_0_0/mnist_design_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_cdma_0_0/mnist_design_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_gpio_0_0/mnist_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_gpio_0_0/mnist_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_gpio_0_0/mnist_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_bram_ctrl_0_0/mnist_design_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_bram_ctrl_1_0/mnist_design_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_axi_bram_ctrl_2_0/mnist_design_axi_bram_ctrl_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_blk_mem_gen_0_0/mnist_design_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_blk_mem_gen_1_0/mnist_design_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_blk_mem_gen_2_0/mnist_design_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_proc_sys_reset_0_0/mnist_design_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_proc_sys_reset_0_0/mnist_design_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_proc_sys_reset_0_0/mnist_design_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_xbar_0/mnist_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_1/bd_e620_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_2/bd_e620_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_3/bd_e620_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_4/bd_e620_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_5/bd_e620_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_6/bd_e620_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_10/bd_e620_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_11/bd_e620_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_12/bd_e620_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_13/bd_e620_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_14/bd_e620_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_15/bd_e620_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_16/bd_e620_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_17/bd_e620_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_18/bd_e620_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_19/bd_e620_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_20/bd_e620_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_21/bd_e620_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_23/bd_e620_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_24/bd_e620_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_25/bd_e620_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_26/bd_e620_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_27/bd_e620_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_28/bd_e620_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_30/bd_e620_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_31/bd_e620_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_32/bd_e620_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_33/bd_e620_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_34/bd_e620_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_35/bd_e620_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_37/bd_e620_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_38/bd_e620_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_39/bd_e620_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_40/bd_e620_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_41/bd_e620_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/bd_0/ip/ip_42/bd_e620_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_xbar_1/mnist_design_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_auto_pc_0/mnist_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/mnist_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/¾G¨|¥à/Desktop/pynq-z2_v1.0.xdc
set_property used_in_implementation false [get_files C:/Users/¾G¨|¥à/Desktop/pynq-z2_v1.0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mnist_design_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mnist_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mnist_design_wrapper_utilization_synth.rpt -pb mnist_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
