# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_auto_pc_0/mnist_design_auto_pc_0.xci
# IP: The module: 'mnist_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_auto_pc_0/mnist_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_auto_pc_0/mnist_design_auto_pc_0.xci
# IP: The module: 'mnist_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mnist_vivado/mnist_vivado.srcs/sources_1/bd/mnist_design/ip/mnist_design_auto_pc_0/mnist_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
